INSERT INTO `product` (`id`, `name`, `price`, `image`, `color`, `quantity`, `style`, `title`, `description`) VALUES
('L1001','CONTINENTAL 80 SHOES',450.00,'CONTINENTAL 80 SHOES.jpg','white',10,'lifestyle','',''),
('L1002','CONTINENTAL 80 SHOES',450.00,'CONTINENTAL 80 SHOES black.jpg','black',10,'lifestyle','',''),
('L1003','NITE JOGGER SHOES',650.00,'NITE JOGGER SHOES.jpg','grey',10,'lifestyle','',''),
('L1004','NITE JOGGER SHOES',650.00,'NITE JOGGER SHOES white.jpg','white',10,'lifestyle','',''),
('L1005','POD-S3.1 SHOES',630.00,'POD-S3.1 SHOES.jpg','white',10,'lifestyle','',''),
('L1006','POD-S3.1 SHOES',630.00,'POD-S3.1 SHOES black.jpg','black',10,'lifestyle','',''),
('L1007','3MC VULC SHOES',280.00,'3MC VULC SHOES.jpg','grey',10,'lifestyle','',''),
('L1008','3MC VULC SHOES',280.00,'3MC VULC SHOES kahki.jpg','kahki',10,'lifestyle','',''),
('L1009','SUPERCOURT SHOES',500.00,'SUPERCOURT SHOES.jpg','black',10,'lifestyle','',''),
('L1010','SUPERCOURT SHOES',280.00,'SUPERCOURT SHOES white.jpg','white',10,'lifestyle','',''),
('L1011','LITE RACER CLN SHOES',260.00,'LITE RACER CLN SHOES.jpg','blue',10,'lifestyle','',''),
('L1012','LITE RACER CLN SHOES',260.00,'LITE RACER CLN SHOES maroon.jpg','maroon',10,'lifestyle','',''),
('L1013','YUNG-96 SHOES',480.00,'YUNG-96 SHOES.jpg','silver',10,'lifestyle','',''),
('L1014','YUNG-96 SHOES',480.00,'YUNG-96 SHOES clear brown.jpg','clear brown',10,'lifestyle','',''),
('L1015','NMD_R1 SHOES',650.00,'NMD_R1 SHOES.jpg','brown',10,'lifestyle','',''),
('L1016','NMD_R1 SHOES',650.00,'NMD_R1 SHOES black.jpg','black',10,'lifestyle','',''),
('L1017','I-5923 SHOES',550.00,'I-5923 SHOES.jpg','black',10,'lifestyle','',''),
('L1018','I-5923 SHOES',550.00,'I-5923 SHOES scarlet.jpg','scarlet',10,'lifestyle','',''),
('L1019','ARKYN SHOES',600.00,'ARKYN SHOES.jpg','blue',10,'lifestyle','',''),
('L1020','ARKYN SHOES',600.00,'ARKYN SHOES pink.jpg','pink',10,'lifestyle','',''),
('L1021','ASWEEGO SHOES',400.00,'ASWEEGO SHOES.jpg','grey',10,'lifestyle','',''),
('L1022','ASWEEGO SHOES',400.00,'ASWEEGO SHOES black.jpg','black',10,'lifestyle','',''),
('L1023','ULTIMAMOTION SHOES',330.00,'ULTIMAMOTION SHOES.jpg','black',10,'lifestyle','',''),
('L1024','ULTIMAMOTION SHOES',330.00,'ULTIMAMOTION SHOES.jpg','white',10,'lifestyle','',''),
('L1025','CLOUDFOAM REFINE SHOES',260.00,'CLOUDFOAM REFINE SHOES.jpg','black',10,'lifestyle','',''),
('L1026','CLOUDFOAM REFINE SHOES',260.00,'CLOUDFOAM REFINE SHOES white.jpg','white',10,'lifestyle','',''),
('L1027','PROPHERE SHOES',520.00,'PROPHERE SHOES.jpg','white',10,'lifestyle','',''),
('L1028','PROPHERE SHOES',520.00,'PROPHERE SHOES black.jpg','black',10,'lifestyle','',''),
('L1029','EQT SUPPORT SHOES',800.00,'EQT SUPPORT SHOES.jpg','white',10,'lifestyle','',''),
('L1030','EQT SUPPORT SHOES',800.00,'EQT SUPPORT SHOES black.jpg','black',10,'lifestyle','',''),
('L1031','STAN SMITH SHOES',420.00,'STAN SMITH SHOES.jpg','white',10,'lifestyle','',''),
('L1032','STAN SMITH SHOES',420.00,'STAN SMITH SHOES white and green.jpg','white and green',10,'lifestyle','',''),
('L1033','QUESTAR FLOW SHOES',350.00,'QUESTAR FLOW SHOES.jpg','black',10,'lifestyle','',''),
('L1034','QUESTAR FLOW SHOES',350.00,'QUESTAR FLOW SHOES grey.jpg','grey',10,'lifestyle','',''),
('L1035','FALCON SHOES',480.00,'FALCON SHOES.jpg','purple',10,'lifestyle','',''),
('L1036','FALCON SHOES',480.00,'FALCON SHOES periwinkle.jpg','periwinkle',10,'lifestyle','',''),
('F1001', 'HOOPS 2.0 MID SHOES', 420.00, 'BasketBlack1boys.jpg', 'black', 10, 'football', 'MID TOP STYLE FOR YOUNG HOOPS FANS.', 'These kids basketball-inspired shoes have a synthetic nubuck upper and a textile lining to provide durable comfort for active feet. 3-Stripes and a rubber cupsole give the shoes classic hoops style.'), 
('F1002', 'DAME 5 SHOES', 500.00, 'Basket1Blackmen.jpg', 'black', 10, 'football', 'B-BALL SHOES BUILT FOR DAMIAN LILLARDS SIGNATURE GAME.','Made to play fresh out of the box, these low top basketball shoes are designed for Damian Lillards signature style. Built with a textile upper, they feature flexible cushioning for lightweight comfort on every step-back jumper. The herringbone outsole lets you change directions on a dime.
Lightweight cushioning
Bounce cushioning provides enhanced comfort and flexibility
Classic comfort
French terry lining for a soft feel and a throwback look
Enhanced traction
Rubber outsole with herringbone pattern for ultimate grip'), 
('F1003', 'HOOPS 2.0 MID SHOES', 420.00, 'BasketWhite1boys.jpg', 'white', 10, 'football', 'MID TOP STYLE FOR YOUNG HOOPS FANS.', 'These kids basketball-inspired shoes have a synthetic nubuck upper and a textile lining to provide durable comfort for active feet. 3-Stripes and a rubber cupsole give the shoes classic hoops style.'), 
('F1004', 'DAME 5 SHOES', 500.00, 'Basket1Whitemen.jpg', 'white', 10, 'football', 'B-BALL SHOES BUILT FOR DAMIAN LILLARDS SIGNATURE GAME.', 'Made to play fresh out of the box, these low top basketball shoes are designed for Damian Lillards signature style. Built with a textile upper, they feature flexible cushioning for lightweight comfort on every step-back jumper. The herringbone outsole lets you change directions on a dime.
Lightweight cushioning
Bounce cushioning provides enhanced comfort and flexibility
Classic comfort
French terry lining for a soft feel and a throwback look
Enhanced traction
Rubber outsole with herringbone pattern for ultimate grip'), 
('F1005', 'ADIDAS D LILLARD 2', 600.00, 'Basket1Whitewomen.jpg', 'white', 10, 'football', '', 'Humbled by each win and starved by each defeat, Damian Lillard’s style of play is the major inspiration for these basketball sneakers. The D Lillard 2 has a supportive FUSEDMESH upper for a secure lockdown as you break to the basket. Bounce delivers energized cushioning through the clutch. The tread pattern pays tribute to his roots and is inspired by the first courts to see his greatness.
The Adidas D Lillard 2 is built to showcase all of Dame’s elite skills. Scoring, passing, and lockdown defense; the Dame 2 helps you do it all on the court.'), 
('F1006', 'PRO ADVERSARY 2019 SHOES', 260.00, 'Basket2Blackgirls.jpg', 'black', 10, 'football', 'DURABLE B-BALL SHOES BUILT FOR COMFORT AND SUPPORT.', 'Get buckets in comfort all season long. These durable basketball shoes feature a soft heel pillow and a foam midsole for enhanced cushioning and Achilles support as you move up and down the court. The herringbone outsole provides extra grip on the blacktop.'),
('F1007', 'MARQUEE BOOST SHOES', 650.00, 'Basket2Gredmen.jpg', 'gred', 10, 'football', 'A CLASSIC B-BALL STYLE DESIGNED FOR EXTRA COMFORT ON THE HARDWOOD.', 'A classic look gets upgraded with modern details. These basketball shoes are built for quickness and agility on the hardwood. They have a moulded ankle collar with a cushioned heel for support and comfort. A responsive midsole returns energy on every jumper while the herringbone outsole provides extra grip as you stop and go on a dime.'), 
('F1008', 'ADIDAS D LILLARD 3', 700.00, 'Basket2Greenwomen.jpg', 'green', 10, 'football', '' , 'Humbled by each win and starved by each defeat, Damian Lillard’s style of play is the major inspiration for these basketball sneakers. The D Lillard 3 has a supportive FUSEDMESH upper for a secure lockdown as you break to the basket. Bounce delivers energized cushioning through the clutch. The tread pattern pays tribute to his roots and is inspired by the first courts to see his greatness.
The Adidas D Lillard 3 is built to showcase all of Dame’s elite skills. Scoring, passing, and lockdown defense; the Dame 3 helps you do it all on the court.'),
('F1009', 'HARDEN VOL.3 SHOES', 440.00, 'Basket2Redboys.jpg', 'red', 10, 'football', 'B-BALL SHOES INSPIRED BY THE CREATIVITY BEHIND JAMES HARDENS STYLE.
', 'Slow down fast. These basketball shoes are inspired by the free-flowing creativity and movement of James Hardens game. The leather upper provides a stable locked-down feel that supports quick changes of direction. A responsive midsole returns energy on every Euro step, and the herringbone outsole gives you extra traction so you can start and stop on a dime.'),
('F1010', 'PRO ADVERSARY 2019 SHOES', 260.00, 'Basket2Redgirls.jpg', 'red', 10, 'football', 'DURABLE B-BALL SHOES BUILT FOR COMFORT AND SUPPORT.', 'Get buckets in comfort all season long. These durable basketball shoes feature a soft heel pillow and a foam midsole for enhanced cushioning and Achilles support as you move up and down the court. The herringbone outsole provides extra grip on the blacktop.'),
('F1011', 'MARQUEE BOOST SHOES', 650.00, 'Basket2Whitemen.jpg', 'white', 10, 'football', 'A CLASSIC B-BALL STYLE DESIGNED FOR EXTRA COMFORT ON THE HARDWOOD.', 'A classic look gets upgraded with modern details. These basketball shoes are built for quickness and agility on the hardwood. They have a moulded ankle collar with a cushioned heel for support and comfort. A responsive midsole returns energy on every jumper while the herringbone outsole provides extra grip as you stop and go on a dime.'),
('F1012', 'PRO VISION SHOES', 320.00, 'Basket3Blackgirls.jpg', 'black', 10, 'football', 'STREETBALL-INSPIRED B-BALL SHOES DESIGNED FOR A LOCKED-DOWN FEEL.', 'These basketball shoes combine a streetball-inspired look with modern details. Designed with a midfoot cage for a locked-down feel, theyre built with flexible midsole cushioning for soft comfort as you attack the paint. The rubber outsole provides extra grip for quick cuts and pivots on the blacktop.'),
('F1013', 'N3XT L3V3L SHOES', 780.00, 'Basket3Blackmen.jpg', 'black', 10, 'football', 'LACELESS B-BALL SHOES DESIGNED FOR A LOCKED-DOWN FEEL.', 'Change directions on a dime. These basketball shoes feature a sock-like construction with a laceless knit upper for a premium locked-down feel. Theyre built with super light Lightstrike cushioning that helps you generate explosive speed for decisive moves up and down the court. A TPU banking barrier offers lateral support for quick side-to-side movement. The herringbone outsole provides extra grip on cuts and pivots.'),
('F1014', 'ADIDAS EXPLOSIVE BOUNCE', 550.00, 'Basket3Redwomen.jpg', 'red', 10, 'football', '', 'Explode to the basket with the Adidas Explosive Bounce. The shoes feature a breathable mesh upper and molded heel piece that keep the foot stable while driving and cutting to the hoop. The energy return of Bounce cushioning helps you push the pace while the clock winds down.'),
('F1015', 'N3XT L3V3L SHOES', 780.00, 'Basket3Whitemen.jpg', 'white', 10, 'football', 'LACELESS B-BALL SHOES DESIGNED FOR A LOCKED-DOWN FEEL.', 'Change directions on a dime. These basketball shoes feature a sock-like construction with a laceless knit upper for a premium locked-down feel. Theyre built with super light Lightstrike cushioning that helps you generate explosive speed for decisive moves up and down the court. A TPU banking barrier offers lateral support for quick side-to-side movement. The herringbone outsole provides extra grip on cuts and pivots.'),
('F1016', 'PRO SPARK 2018 SHOES', 200.00, 'Basket4Blackgirls.jpg', 'black', 10, 'football', 'SHOES DESIGNED FOR SEASON-LONG COMFORT AND DURABILITY.', 'Built to keep you comfortable as you hit clutch shots down the stretch, these kids shoes feature a cushioned midsole and a padded heel for exceptional comfort. The breathable upper and synthetic toe overlay offer durability and lockdown as you suffocate opposition ball handlers with side-to-side movement on every possession.'),
('F1017', 'PRO BOUNCE MADNESS LOW 2019 SHOES', 480.00, 'Basket4Blackmen.jpg', 'black', 10, 'football', 'LOW TOP B-BALL SHOES DESIGNED FOR AGILITY AND QUICKNESS.', 'Shake defenders all through the game long. Built for agility, these basketball shoes have a textile upper with a cushioned collar for enhanced ankle support. Responsive cushioning in the midsole lets you hustle up and down the court in comfort. A TPU overlay offers lateral stability for quick side-to-side movement. The herringbone outsole provides extra grip as you cut and pivot to the basket.'),
('F1018', 'MARVELS CAPTAIN MARVEL | PRO', 380.00, 'Basket4Blueboys.jpg', 'blue', 10, 'football', 'STREETBALL-INSPIRED B-BALL SHOES DESIGNED FOR A LOCKED-DOWN FEEL.', 'These junior boys basketball shoes mix a streetball-inspired look with modern details. Designed with a midfoot cage for a locked-down feel, they are built with flexible midsole cushioning for soft comfort as you attack the paint. The rubber outsole provides extra grip for quick cuts and pivots on the blacktop.'),
('F1019', 'PRO SPARK 2018 SHOES', 200.00, 'Basket4Bluegirls.jpg', 'blue', 10, 'football', 'LOW TOP B-BALL SHOES DESIGNED FOR AGILITY AND QUICKNESS.', 'Shake defenders all through the game long. Built for agility, these basketball shoes have a textile upper with a cushioned collar for enhanced ankle support. Responsive cushioning in the midsole lets you hustle up and down the court in comfort. A TPU overlay offers lateral stability for quick side-to-side movement. The herringbone outsole provides extra grip as you cut and pivot to the basket.'),
('F1020', 'ADIDAS D ROSE 7', 850.00, 'Basket4Bluewomen.jpg', 'blue', 10, 'football', '', 'The Adidas D Rose 7 is the third signature shoe of Derrick Rose to have Boost technology in the midsole. It delivers impact protection like no other. The traction of the shoe features a herringbone pattern, letting the player do multidirectional footwork without slipping.
High-top basketball shoes are said to provide more ankle support to hoopers. However, there are those who prefer low-top basketball sneakers because of the increased mobility that they afford. At the same price of $140, wearers may try the low-collared Boost-equipped Harden Vol 3. If mid-top shoes are an alternative, the Adidas Dame 5 is a great go.'),
('F1021', 'PRO SPARK 2018 SHOES', 200.00, 'Basket4Gredgirls.jpg', 'gred', 10, 'football', 'LOW TOP B-BALL SHOES DESIGNED FOR AGILITY AND QUICKNESS.', 'Shake defenders all through the game long. Built for agility, these basketball shoes have a textile upper with a cushioned collar for enhanced ankle support. Responsive cushioning in the midsole lets you hustle up and down the court in comfort. A TPU overlay offers lateral stability for quick side-to-side movement. The herringbone outsole provides extra grip as you cut and pivot to the basket.'),
('F1022', 'PRO BOUNCE MADNESS LOW 2019 SHOES', 480.00, 'Basket4Gredmen.jpg', 'gred', 10, 'football', 'LOW TOP B-BALL SHOES DESIGNED FOR AGILITY AND QUICKNESS.', 'Shake defenders all through the game long. Built for agility, these basketball shoes have a textile upper with a cushioned collar for enhanced ankle support. Responsive cushioning in the midsole lets you hustle up and down the court in comfort. A TPU overlay offers lateral stability for quick side-to-side movement. The herringbone outsole provides extra grip as you cut and pivot to the basket.'),
('F1023', 'PRO BOUNCE MADNESS LOW 2019 SHOES', 480.00, 'Basket4Whitemen.jpg', 'white', 10, 'football', 'LOW TOP B-BALL SHOES DESIGNED FOR AGILITY AND QUICKNESS.', 'Shake defenders all through the game long. Built for agility, these basketball shoes have a textile upper with a cushioned collar for enhanced ankle support. Responsive cushioning in the midsole lets you hustle up and down the court in comfort. A TPU overlay offers lateral stability for quick side-to-side movement. The herringbone outsole provides extra grip as you cut and pivot to the basket.'),
('F1024', 'HARDEN VOL.3 SHOES', 440.00, 'Basket5Blackmen.jpg', 'black', 10, 'football', 'B-BALL SHOES INSPIRED BY THE CREATIVITY BEHIND JAMES HARDENS STYLE.', 'Slow down fast. These basketball shoes are inspired by the free-flowing creativity and movement of James Hardens game. The leather upper provides a stable locked-down feel that supports quick changes of direction. A responsive midsole returns energy on every Euro step, and the herringbone outsole gives you extra traction so you can start and stop on a dime.'),
('F1025', 'ADIDAS D ROSE 6 BOOST', 650.00, 'Basket5Blackwomen.jpg', 'black', 10, 'football', '', 'The Adidas D Rose 6 Boost is a sneaker packed with Boost technology in the midsole for impact absorption. Something new with the design of this shoe is the external strap on the heel counter. It cups the ankle to make sure the feet is not moving around. Another would be the StableFrame in the midsole that cradles the Boost technology.
Boost is a must-have for most basketball hoopers. James Harden’s third Adidas basketball shoe features the exposed full-length Boost for cushioning. Unlike the Boost in the D Rose 6, the Boost in James Hardens signature basketball shoes are bouncier.'),
('F1026', 'MARQUEE BOOST SHOES', 352.00, 'Basket5Bluegirls.jpg', 'blue', 10, 'football','CLASSIC B-BALL SHOES DESIGNED FOR AGILITY ON THE COURT.', 'Updating a classic look with modern details, these low-cut basketball shoes are built for quickness and agility on the hardwood. They feature a molded ankle collar with a cushioned heel for support and comfort. A responsive midsole returns energy on every jumper. The herringbone outsole provides extra grip as you stop and go on a dime.
Endless energyEndless energy
Boost is our most responsive cushioning ever, delivering incredible energy return: The more energy you give, the more you get
Enhanced traction
The zonal herringbone outsole adds extra grip on the court
Padded support
The molded, padded ankle collar offers enhanced comfort'),
('F1027', 'EXPLOSIVE IGNITE 2018 WIDE SHOES', 250.00, 'Basket5Gredboys.jpg', 'gred', 10, 'football', 'COMFORTABLE SHOES BUILT WITH EXTRA MIDFOOT STABILITY.', 'These kids shoes are built to help little ones improve their game in comfort. A wider fit offers extra comfort and stability for side-to-side movement, while enhanced cushioning in the midsole and sockliner lets them work on their game all day long. A lightweight upper adds durability to power through the entire season.'),
('F1028', 'HARDEN VOL.3 SHOES', 650.00, 'Basket5Gredmen.jpg', 'gred', 10, 'football', 'B-BALL SHOES FOR STOP-AND-START MOVES IN JAMES HARDENS STYLE.', 'Slow down fast. Inspired by his ability to change speed and create space from defenders, these basketball shoes are designed for James Hardens signature style. They are built with a leather upper for a locked-down feel that supports quick changes of direction. A responsive midsole returns energy on every Euro step. The herringbone outsole provides extra traction as you start and stop on a dime.'),
('F1029', 'MARQUEE BOOST SHOES', 352.00, 'Basket5Redgirls.jpg', 'red', 10, 'football', 'CLASSIC B-BALL SHOES DESIGNED FOR AGILITY ON THE COURT.', 'Updating a classic look with modern details, these low-cut basketball shoes are built for quickness and agility on the hardwood. They feature a molded ankle collar with a cushioned heel for support and comfort. A responsive midsole returns energy on every jumper. The herringbone outsole provides extra grip as you stop and go on a dime.
Endless energyEndless energy
Boost is our most responsive cushioning ever, delivering incredible energy return: The more energy you give, the more you get
Enhanced traction
The zonal herringbone outsole adds extra grip on the court
Padded support
The molded, padded ankle collar offers enhanced comfort'),
('F1030', 'EXPLOSIVE IGNITE 2018 WIDE SHOES', 250.00, 'Basket5Gredboys.jpg', 'gred', 10, 'football', 'COMFORTABLE SHOES BUILT WITH EXTRA MIDFOOT STABILITY.', 'These kids shoes are built to help little ones improve their game in comfort. A wider fit offers extra comfort and stability for side-to-side movement, while enhanced cushioning in the midsole and sockliner lets them work on their game all day long. A lightweight upper adds durability to power through the entire season.'),
('T1001', 'ALPHABOUNCE 1 PARLEY SHOES', 294.00, 'TrainingKidsBoyAlphabounce1Parley.jpg', 'black', 10, 'training', 'CUSHIONED SHOES MADE WITH PARLEY OCEAN PLASTIC™ YARN.', 'These juniors running shoes are designed with a seamless mesh upper that supports and flexes with your foot through the gait cycle. Underfoot, Bounce provides comfortable cushioning.
adidas is dedicated to creating products in ways that minimise their environmental impact. This product is created with yarn made in collaboration with Parley for the Oceans. Some of the yarn features Parley Ocean Plastic™ which is made from recycled waste, intercepted from beaches and coastal communities before it reaches the ocean.'), 
('T1002', 'PUREBOOST GO SHOES', 440.00, 'TrainingKidsBoyPureboostGo.jpg', 'grey', 10, 'training', 'LIGHTWEIGHT, SUPPORTIVE SHOES FOR CITY RUNNING.', 'Designed for the uneven sidewalks, rain-slick pavement and unexpected obstacles of urban running. These juniors neutral shoes have a wider forefoot platform and higher heel for increased stability. A lightweight knit upper hugs and supports the foot. Responsive cushioning returns energy with every stride.'), 
('T1003', 'RAPIDARUN KNIT SHOES', 226.00, 'TrainingKidsBoyRapidunKnit.jpg', 'black', 10, 'training', 'CUSHIONING RUNNING SHOES FOR A COMFORTABLE RIDE.', 'These juniors shoes offer performance with every stride. The adaptive knit upper moves naturally with every footstrike, while a Cloudfoam midsole offers pillow-soft cushioning for long-lasting comfort. A running-specific outsole and targeted support in key areas round out the design.'), 
('T1004', 'RAPIDARUN LACELESS SHOES', 300.00, 'TrainingKidsBoyRapidunLaceles.jpg', 'black', 10, 'training', 'LIGHTWEIGHT, SUPPORTIVE SHOES FOR CITY RUNNING.', 'Designed for the uneven sidewalks, rain-slick pavement and unexpected obstacles of urban running. These juniors neutral shoes have a wider forefoot platform and higher heel for increased stability. A lightweight knit upper hugs and supports the foot. Responsive cushioning returns energy with every stride.'), 
('T1005', 'ULTRABOOST SHOES', 800.00, 'TrainingKidsBoyUltraboost.jpg', 'grey', 10, 'training', 'JUNIORS RUNNING SHOES FOR RESPONSIVE ENERGY RETURN.', 'Whether you are sprinting past competitors or hanging with the pack, these juniors running shoes are designed to help you reach your goals. They have responsive cushioning for endless energy return. The knit upper wraps around your foot for a supportive feel while the grippy rubber outsole delivers traction on unpredictable surfaces.'), 
('T1006', 'ALPHABOUNCE BEYOND SHOES', 300.00, 'TrainingKidsGirlAlphabounceBeyond.jpg', 'blue', 10, 'training', 'NEUTRAL RUNNING SHOES WITH A SOCK-LIKE FIT AND CUSHIONED COMFORT.', 'With the smooth construction of a Forgedmesh upper, these juniors running shoes deliver a comfortable, foot-hugging fit. Bounce cushioning provides flexible comfort for leaps and sprints during after-school sports.'), 
('T1007', 'ALPHABOUNCE INSTINCT SHOES', 259.00, 'TrainingKidsGirlAlphabounceInstint.jpg', 'grey', 10, 'training', 'VERSATILE RUNNING SHOES WITH TARGETED SUPPORT.', 'Made for cross training, these juniors neutral running shoes have a seamless, supportive mesh upper. Strategic zones of reinforcement support lateral as well as linear movement. The flexible midsole offers enhanced cushioning and allows the foot to move naturally.'), 
('T1008', '24/7 SHOES', 360.00, 'TrainingWomen24shoes.jpg', 'grey', 10, 'training', 'LIGHTWEIGHT TRAINING SHOES WITH STEP-IN COMFORT.', 'Made for cross training, these juniors neutral running shoes have a seamless, supportive mesh upper. Strategic zones of reinforcement support lateral as well as linear movement. The flexible midsole offers enhanced cushioning and allows the foot to move naturally.'),
('T1009', '24/7 SHOES', 360.00, 'TrainingWomen24shoes1.jpg', 'black', 10, 'training', 'LIGHTWEIGHT TRAINING SHOES WITH STEP-IN COMFORT.', 'Made for cross training, these juniors neutral running shoes have a seamless, supportive mesh upper. Strategic zones of reinforcement support lateral as well as linear movement. The flexible midsole offers enhanced cushioning and allows the foot to move naturally.'),
('T1010', 'CRAZYTRAIN ELITE SHOES', 455.00, 'TrainingWomenCrazyTrainElite.jpg', 'black', 10, 'training', 'MULTISPORT TRAINING SHOES WITH RESPONSIVE CUSHIONING.', 'These shoes have a training-specific design that supports multidirectional movement. The lightweight mesh upper hugs the foot with a sock-like fit. Built-in midfoot support provides stability, and forefoot flex gives you a wide range of motion. Responsive cushioning returns energy to your stride.'),
('T1011', 'CRAZYTRAIN LT SHOES', 140.00, 'TrainingWomenCrazyTrainLT1.jpg', 'red', 10, 'training', 'LIGHTWEIGHT TURF SHOES MADE FOR CROSS TRAINING.', 'Push past plateaus in these men or women turf training shoes. Dual-density Bounce for energised comfort and a lightweight build with a breathable mesh upper helps keep you going. The PU overlays and rubber outsole add stability and traction for quick direction changes.'),
('T1012', 'EDGEBOUNCE SHOES', 266.00, 'TrainingWomenCrazyTrainPro.jpg', 'black', 10, 'training', 'INSPIRED BY CREATORS, DESIGNED TO STAND OUT, CURATED FOR YOU.', 'Part of a statement collection inspired by Stella McCartney, these neutral running shoes are geared for gym floors or pavement. The womens-specific design features a wider forefoot and heel platform to deliver stability while cross training. The shoes have a stretch mesh upper that offers foot-cradling comfort.'),
('T1013', 'EDGEBOUNCE SHOES', 266.00, 'TrainingWomenEdgebounce1.jpg', 'white', 10, 'training', 'INSPIRED BY CREATORS, DESIGNED TO STAND OUT, CURATED FOR YOU.', 'Part of a statement collection inspired by Stella McCartney, these neutral running shoes are geared for gym floors or pavement. The womens-specific design features a wider forefoot and heel platform to deliver stability while cross training. The shoes have a stretch mesh upper that offers foot-cradling comfort.'),
('T1014', 'PUREBOOST X TR 3.0 LL SHOES', 280.00, 'TrainingWomenPureboostXTR3.0LL1.jpg', 'blue', 10, 'training', 'LACELESS HIGH CUTS WITH A WOMENS-SPECIFIC ARCH DESIGN.
', 'Made for the athlete who likes to mix it up, these shoes have a progressive design, with a womens-specific arch that cradles the foot for a unique compression fit. The slip-on shoes have a knit upper with wraparound bands that hug the foot for support and stretch in any direction.'),
('T1015', 'CRAZYTRAIN ELITE SHOES', 240.00, 'TrainingWomenSolarLT1.jpg', 'white', 10, 'training', 'LIGHTWEIGHT SHOES READY FOR ANY TYPE OF WORKOUT.', 'Versatile enough for a variety of workouts, these shoes are made for the athlete who mixes up barbell exercises one day with agility drills or speedwork the next. The textile upper is lightweight and flexible while providing the lockdown you need when moving side-to-side. It rides on a cushioned midsole that feels springy and flexible.'),
('T1016', 'ULTRABOOST X ALL TERRAIN', 700.00, 'TrainingWomenUltraboostXAllTerrain.jpg', 'grey', 10, 'training', 'MODERN SLIP-ON RUNNING SHOES CREATED WITH STELLA MCCARTNEY.', 'Innovative style thats pure Stella. These streamlined running shoes have a slip-on design that wraps the foot in supportive comfort. With a mid cut, they ride on a rubber outsole that grips the pavement in wet conditions. Matte and shiny overlays add an eye-catching finish.'),
('T1017', 'TERREX TRACEROCKER SHOES', 350.00, 'TraningTerrexTracerocker.jpg', 'black', 10, 'training', 'CORE BLACK/CORE BLACK/UTILITY BLACK', 'Lightweight and durable, these mens trail running shoes are designed for light trails. They feature a breathable mesh upper and EVA midsole cushioning. A rugged TRAXION™ outsole maximises grip in all directions.'),
('B1001', 'HOOPS 2.0 MID SHOES', 420.00, 'BasketBlack1boys.jpg', 'black', 10, 'football', 'MID TOP STYLE FOR YOUNG HOOPS FANS.', 'These kids basketball-inspired shoes have a synthetic nubuck upper and a textile lining to provide durable comfort for active feet. 3-Stripes and a rubber cupsole give the shoes classic hoops style.'), 
('B1002', 'DAME 5 SHOES', 500.00, 'Basket1Blackmen.jpg', 'black', 10, 'football', 'B-BALL SHOES BUILT FOR DAMIAN LILLARDS SIGNATURE GAME.','Made to play fresh out of the box, these low top basketball shoes are designed for Damian Lillards signature style. Built with a textile upper, they feature flexible cushioning for lightweight comfort on every step-back jumper. The herringbone outsole lets you change directions on a dime.
Lightweight cushioning
Bounce cushioning provides enhanced comfort and flexibility
Classic comfort
French terry lining for a soft feel and a throwback look
Enhanced traction
Rubber outsole with herringbone pattern for ultimate grip'), 
('B1003', 'HOOPS 2.0 MID SHOES', 420.00, 'BasketWhite1boys.jpg', 'white', 10, 'football', 'MID TOP STYLE FOR YOUNG HOOPS FANS.', 'These kids basketball-inspired shoes have a synthetic nubuck upper and a textile lining to provide durable comfort for active feet. 3-Stripes and a rubber cupsole give the shoes classic hoops style.'), 
('B1004', 'DAME 5 SHOES', 500.00, 'Basket1Whitemen.jpg', 'white', 10, 'football', 'B-BALL SHOES BUILT FOR DAMIAN LILLARDS SIGNATURE GAME.', 'Made to play fresh out of the box, these low top basketball shoes are designed for Damian Lillards signature style. Built with a textile upper, they feature flexible cushioning for lightweight comfort on every step-back jumper. The herringbone outsole lets you change directions on a dime.
Lightweight cushioning
Bounce cushioning provides enhanced comfort and flexibility
Classic comfort
French terry lining for a soft feel and a throwback look
Enhanced traction
Rubber outsole with herringbone pattern for ultimate grip'), 
('B1005', 'ADIDAS D LILLARD 2', 600.00, 'Basket1Whitewomen.jpg', 'white', 10, 'football', '', 'Humbled by each win and starved by each defeat, Damian Lillard’s style of play is the major inspiration for these basketball sneakers. The D Lillard 2 has a supportive FUSEDMESH upper for a secure lockdown as you break to the basket. Bounce delivers energized cushioning through the clutch. The tread pattern pays tribute to his roots and is inspired by the first courts to see his greatness.
The Adidas D Lillard 2 is built to showcase all of Dame’s elite skills. Scoring, passing, and lockdown defense; the Dame 2 helps you do it all on the court.'), 
('B1006', 'PRO ADVERSARY 2019 SHOES', 260.00, 'Basket2Blackgirls.jpg', 'black', 10, 'football', 'DURABLE B-BALL SHOES BUILT FOR COMFORT AND SUPPORT.', 'Get buckets in comfort all season long. These durable basketball shoes feature a soft heel pillow and a foam midsole for enhanced cushioning and Achilles support as you move up and down the court. The herringbone outsole provides extra grip on the blacktop.'),
('B1007', 'MARQUEE BOOST SHOES', 650.00, 'Basket2Gredmen.jpg', 'grey', 10, 'football', 'A CLASSIC B-BALL STYLE DESIGNED FOR EXTRA COMFORT ON THE HARDWOOD.', 'A classic look gets upgraded with modern details. These basketball shoes are built for quickness and agility on the hardwood. They have a moulded ankle collar with a cushioned heel for support and comfort. A responsive midsole returns energy on every jumper while the herringbone outsole provides extra grip as you stop and go on a dime.'), 
('B1008', 'ADIDAS D LILLARD 3', 700.00, 'Basket2Greenwomen.jpg', 'green', 10, 'football', '' , 'Humbled by each win and starved by each defeat, Damian Lillard’s style of play is the major inspiration for these basketball sneakers. The D Lillard 3 has a supportive FUSEDMESH upper for a secure lockdown as you break to the basket. Bounce delivers energized cushioning through the clutch. The tread pattern pays tribute to his roots and is inspired by the first courts to see his greatness.
The Adidas D Lillard 3 is built to showcase all of Dame’s elite skills. Scoring, passing, and lockdown defense; the Dame 3 helps you do it all on the court.'),
('B1009', 'HARDEN VOL.3 SHOES', 440.00, 'Basket2Redboys.jpg', 'red', 10, 'football', 'B-BALL SHOES INSPIRED BY THE CREATIVITY BEHIND JAMES HARDENS STYLE.
', 'Slow down fast. These basketball shoes are inspired by the free-flowing creativity and movement of James Hardens game. The leather upper provides a stable locked-down feel that supports quick changes of direction. A responsive midsole returns energy on every Euro step, and the herringbone outsole gives you extra traction so you can start and stop on a dime.'),
('B1010', 'PRO ADVERSARY 2019 SHOES', 260.00, 'Basket2Redgirls.jpg', 'red', 10, 'football', 'DURABLE B-BALL SHOES BUILT FOR COMFORT AND SUPPORT.', 'Get buckets in comfort all season long. These durable basketball shoes feature a soft heel pillow and a foam midsole for enhanced cushioning and Achilles support as you move up and down the court. The herringbone outsole provides extra grip on the blacktop.'),
('B1011', 'MARQUEE BOOST SHOES', 650.00, 'Basket2Whitemen.jpg', 'white', 10, 'football', 'A CLASSIC B-BALL STYLE DESIGNED FOR EXTRA COMFORT ON THE HARDWOOD.', 'A classic look gets upgraded with modern details. These basketball shoes are built for quickness and agility on the hardwood. They have a moulded ankle collar with a cushioned heel for support and comfort. A responsive midsole returns energy on every jumper while the herringbone outsole provides extra grip as you stop and go on a dime.'),
('B1012', 'PRO VISION SHOES', 320.00, 'Basket3Blackgirls.jpg', 'black', 10, 'football', 'STREETBALL-INSPIRED B-BALL SHOES DESIGNED FOR A LOCKED-DOWN FEEL.', 'These basketball shoes combine a streetball-inspired look with modern details. Designed with a midfoot cage for a locked-down feel, theyre built with flexible midsole cushioning for soft comfort as you attack the paint. The rubber outsole provides extra grip for quick cuts and pivots on the blacktop.'),
('B1013', 'N3XT L3V3L SHOES', 780.00, 'Basket3Blackmen.jpg', 'black', 10, 'football', 'LACELESS B-BALL SHOES DESIGNED FOR A LOCKED-DOWN FEEL.', 'Change directions on a dime. These basketball shoes feature a sock-like construction with a laceless knit upper for a premium locked-down feel. Theyre built with super light Lightstrike cushioning that helps you generate explosive speed for decisive moves up and down the court. A TPU banking barrier offers lateral support for quick side-to-side movement. The herringbone outsole provides extra grip on cuts and pivots.'),
('B1014', 'ADIDAS EXPLOSIVE BOUNCE', 550.00, 'Basket3Redwomen.jpg', 'red', 10, 'football', '', 'Explode to the basket with the Adidas Explosive Bounce. The shoes feature a breathable mesh upper and molded heel piece that keep the foot stable while driving and cutting to the hoop. The energy return of Bounce cushioning helps you push the pace while the clock winds down.'),
('B1015', 'N3XT L3V3L SHOES', 780.00, 'Basket3Whitemen.jpg', 'white', 10, 'football', 'LACELESS B-BALL SHOES DESIGNED FOR A LOCKED-DOWN FEEL.', 'Change directions on a dime. These basketball shoes feature a sock-like construction with a laceless knit upper for a premium locked-down feel. Theyre built with super light Lightstrike cushioning that helps you generate explosive speed for decisive moves up and down the court. A TPU banking barrier offers lateral support for quick side-to-side movement. The herringbone outsole provides extra grip on cuts and pivots.'),
('B1016', 'PRO SPARK 2018 SHOES', 200.00, 'Basket4Blackgirls.jpg', 'black', 10, 'football', 'SHOES DESIGNED FOR SEASON-LONG COMFORT AND DURABILITY.', 'Built to keep you comfortable as you hit clutch shots down the stretch, these kids shoes feature a cushioned midsole and a padded heel for exceptional comfort. The breathable upper and synthetic toe overlay offer durability and lockdown as you suffocate opposition ball handlers with side-to-side movement on every possession.'),
('B1017', 'PRO BOUNCE MADNESS LOW 2019 SHOES', 480.00, 'Basket4Blackmen.jpg', 'black', 10, 'football', 'LOW TOP B-BALL SHOES DESIGNED FOR AGILITY AND QUICKNESS.', 'Shake defenders all through the game long. Built for agility, these basketball shoes have a textile upper with a cushioned collar for enhanced ankle support. Responsive cushioning in the midsole lets you hustle up and down the court in comfort. A TPU overlay offers lateral stability for quick side-to-side movement. The herringbone outsole provides extra grip as you cut and pivot to the basket.'),
('B1018', 'MARVELS CAPTAIN MARVEL | PRO', 380.00, 'Basket4Blueboys.jpg', 'blue', 10, 'football', 'STREETBALL-INSPIRED B-BALL SHOES DESIGNED FOR A LOCKED-DOWN FEEL.', 'These junior boys basketball shoes mix a streetball-inspired look with modern details. Designed with a midfoot cage for a locked-down feel, they are built with flexible midsole cushioning for soft comfort as you attack the paint. The rubber outsole provides extra grip for quick cuts and pivots on the blacktop.'),
('B1019', 'PRO SPARK 2018 SHOES', 200.00, 'Basket4Bluegirls.jpg', 'blue', 10, 'football', 'LOW TOP B-BALL SHOES DESIGNED FOR AGILITY AND QUICKNESS.', 'Shake defenders all through the game long. Built for agility, these basketball shoes have a textile upper with a cushioned collar for enhanced ankle support. Responsive cushioning in the midsole lets you hustle up and down the court in comfort. A TPU overlay offers lateral stability for quick side-to-side movement. The herringbone outsole provides extra grip as you cut and pivot to the basket.'),
('B1020', 'ADIDAS D ROSE 7', 850.00, 'Basket4Bluewomen.jpg', 'blue', 10, 'football', '', 'The Adidas D Rose 7 is the third signature shoe of Derrick Rose to have Boost technology in the midsole. It delivers impact protection like no other. The traction of the shoe features a herringbone pattern, letting the player do multidirectional footwork without slipping.
High-top basketball shoes are said to provide more ankle support to hoopers. However, there are those who prefer low-top basketball sneakers because of the increased mobility that they afford. At the same price of $140, wearers may try the low-collared Boost-equipped Harden Vol 3. If mid-top shoes are an alternative, the Adidas Dame 5 is a great go.'),
('B1021', 'PRO SPARK 2018 SHOES', 200.00, 'Basket4Gredgirls.jpg', 'grey', 10, 'football', 'LOW TOP B-BALL SHOES DESIGNED FOR AGILITY AND QUICKNESS.', 'Shake defenders all through the game long. Built for agility, these basketball shoes have a textile upper with a cushioned collar for enhanced ankle support. Responsive cushioning in the midsole lets you hustle up and down the court in comfort. A TPU overlay offers lateral stability for quick side-to-side movement. The herringbone outsole provides extra grip as you cut and pivot to the basket.'),
('B1022', 'PRO BOUNCE MADNESS LOW 2019 SHOES', 480.00, 'Basket4Gredmen.jpg', 'grey', 10, 'football', 'LOW TOP B-BALL SHOES DESIGNED FOR AGILITY AND QUICKNESS.', 'Shake defenders all through the game long. Built for agility, these basketball shoes have a textile upper with a cushioned collar for enhanced ankle support. Responsive cushioning in the midsole lets you hustle up and down the court in comfort. A TPU overlay offers lateral stability for quick side-to-side movement. The herringbone outsole provides extra grip as you cut and pivot to the basket.'),
('B1023', 'PRO BOUNCE MADNESS LOW 2019 SHOES', 480.00, 'Basket4Whitemen.jpg', 'white', 10, 'football', 'LOW TOP B-BALL SHOES DESIGNED FOR AGILITY AND QUICKNESS.', 'Shake defenders all through the game long. Built for agility, these basketball shoes have a textile upper with a cushioned collar for enhanced ankle support. Responsive cushioning in the midsole lets you hustle up and down the court in comfort. A TPU overlay offers lateral stability for quick side-to-side movement. The herringbone outsole provides extra grip as you cut and pivot to the basket.'),
('B1024', 'HARDEN VOL.3 SHOES', 440.00, 'Basket5Blackmen.jpg', 'black', 10, 'football', 'B-BALL SHOES INSPIRED BY THE CREATIVITY BEHIND JAMES HARDENS STYLE.', 'Slow down fast. These basketball shoes are inspired by the free-flowing creativity and movement of James Hardens game. The leather upper provides a stable locked-down feel that supports quick changes of direction. A responsive midsole returns energy on every Euro step, and the herringbone outsole gives you extra traction so you can start and stop on a dime.'),
('B1025', 'ADIDAS D ROSE 6 BOOST', 650.00, 'Basket5Blackwomen.jpg', 'black', 10, 'football', '', 'The Adidas D Rose 6 Boost is a sneaker packed with Boost technology in the midsole for impact absorption. Something new with the design of this shoe is the external strap on the heel counter. It cups the ankle to make sure the feet is not moving around. Another would be the StableFrame in the midsole that cradles the Boost technology.
Boost is a must-have for most basketball hoopers. James Harden’s third Adidas basketball shoe features the exposed full-length Boost for cushioning. Unlike the Boost in the D Rose 6, the Boost in James Hardens signature basketball shoes are bouncier.'),
('B1026', 'MARQUEE BOOST SHOES', 352.00, 'Basket5Bluegirls.jpg', 'blue', 10, 'football','CLASSIC B-BALL SHOES DESIGNED FOR AGILITY ON THE COURT.', 'Updating a classic look with modern details, these low-cut basketball shoes are built for quickness and agility on the hardwood. They feature a molded ankle collar with a cushioned heel for support and comfort. A responsive midsole returns energy on every jumper. The herringbone outsole provides extra grip as you stop and go on a dime.
Endless energyEndless energy
Boost is our most responsive cushioning ever, delivering incredible energy return: The more energy you give, the more you get
Enhanced traction
The zonal herringbone outsole adds extra grip on the court
Padded support
The molded, padded ankle collar offers enhanced comfort'),
('B1027', 'EXPLOSIVE IGNITE 2018 WIDE SHOES', 250.00, 'Basket5Gredboys.jpg', 'grey', 10, 'football', 'COMFORTABLE SHOES BUILT WITH EXTRA MIDFOOT STABILITY.', 'These kids shoes are built to help little ones improve their game in comfort. A wider fit offers extra comfort and stability for side-to-side movement, while enhanced cushioning in the midsole and sockliner lets them work on their game all day long. A lightweight upper adds durability to power through the entire season.'),
('B1028', 'HARDEN VOL.3 SHOES', 650.00, 'Basket5Gredmen.jpg', 'grey', 10, 'football', 'B-BALL SHOES FOR STOP-AND-START MOVES IN JAMES HARDENS STYLE.', 'Slow down fast. Inspired by his ability to change speed and create space from defenders, these basketball shoes are designed for James Hardens signature style. They are built with a leather upper for a locked-down feel that supports quick changes of direction. A responsive midsole returns energy on every Euro step. The herringbone outsole provides extra traction as you start and stop on a dime.'),
('B1029', 'MARQUEE BOOST SHOES', 352.00, 'Basket5Redgirls.jpg', 'red', 10, 'football', 'CLASSIC B-BALL SHOES DESIGNED FOR AGILITY ON THE COURT.', 'Updating a classic look with modern details, these low-cut basketball shoes are built for quickness and agility on the hardwood. They feature a molded ankle collar with a cushioned heel for support and comfort. A responsive midsole returns energy on every jumper. The herringbone outsole provides extra grip as you stop and go on a dime.
Endless energyEndless energy
Boost is our most responsive cushioning ever, delivering incredible energy return: The more energy you give, the more you get
Enhanced traction
The zonal herringbone outsole adds extra grip on the court
Padded support
The molded, padded ankle collar offers enhanced comfort'),
('B1030', 'EXPLOSIVE IGNITE 2018 WIDE SHOES', 250.00, 'Basket5Gredboys.jpg', 'grey', 10, 'football', 'COMFORTABLE SHOES BUILT WITH EXTRA MIDFOOT STABILITY.', 'These kids shoes are built to help little ones improve their game in comfort. A wider fit offers extra comfort and stability for side-to-side movement, while enhanced cushioning in the midsole and sockliner lets them work on their game all day long. A lightweight upper adds durability to power through the entire season.');