INSERT INTO `product` (`id`, `name`, `price`, `image`, `color`, `quantity`, `style`, `title`, `description`) VALUES
('B1001', 'HOOPS 2.0 MID SHOES', 420.00, 'BasketBlack1boys.jpg', 'black', 10, 'basketball', 'MID TOP STYLE FOR YOUNG HOOPS FANS.', 'These kids basketball-inspired shoes have a synthetic nubuck upper and a textile lining to provide durable comfort for active feet. 3-Stripes and a rubber cupsole give the shoes classic hoops style.'), 
('B1002', 'DAME 5 SHOES', 500.00, 'Basket1Blackmen.jpg', 'black', 10, 'basketball', 'B-BALL SHOES BUILT FOR DAMIAN LILLARDS SIGNATURE GAME.','Made to play fresh out of the box, these low top basketball shoes are designed for Damian Lillards signature style. Built with a textile upper, they feature flexible cushioning for lightweight comfort on every step-back jumper. The herringbone outsole lets you change directions on a dime.
Lightweight cushioning
Bounce cushioning provides enhanced comfort and flexibility
Classic comfort
French terry lining for a soft feel and a throwback look
Enhanced traction
Rubber outsole with herringbone pattern for ultimate grip'), 
('B1003', 'HOOPS 2.0 MID SHOES', 420.00, 'BasketWhite1boys.jpg', 'white', 10, 'basketball', 'MID TOP STYLE FOR YOUNG HOOPS FANS.', 'These kids basketball-inspired shoes have a synthetic nubuck upper and a textile lining to provide durable comfort for active feet. 3-Stripes and a rubber cupsole give the shoes classic hoops style.'), 
('B1004', 'DAME 5 SHOES', 500.00, 'Basket1Whitemen.jpg', 'white', 10, 'basketball', 'B-BALL SHOES BUILT FOR DAMIAN LILLARDS SIGNATURE GAME.', 'Made to play fresh out of the box, these low top basketball shoes are designed for Damian Lillards signature style. Built with a textile upper, they feature flexible cushioning for lightweight comfort on every step-back jumper. The herringbone outsole lets you change directions on a dime.
Lightweight cushioning
Bounce cushioning provides enhanced comfort and flexibility
Classic comfort
French terry lining for a soft feel and a throwback look
Enhanced traction
Rubber outsole with herringbone pattern for ultimate grip'), 
('B1005', 'ADIDAS D LILLARD 2', 600.00, 'Basket1Whitewomen.jpg', 'white', 10, 'basketball', '', 'Humbled by each win and starved by each defeat, Damian Lillard’s style of play is the major inspiration for these basketball sneakers. The D Lillard 2 has a supportive FUSEDMESH upper for a secure lockdown as you break to the basket. Bounce delivers energized cushioning through the clutch. The tread pattern pays tribute to his roots and is inspired by the first courts to see his greatness.
The Adidas D Lillard 2 is built to showcase all of Dame’s elite skills. Scoring, passing, and lockdown defense; the Dame 2 helps you do it all on the court.'), 
('B1006', 'PRO ADVERSARY 2019 SHOES', 260.00, 'Basket2Blackgirls.jpg', 'black', 10, 'basketball', 'DURABLE B-BALL SHOES BUILT FOR COMFORT AND SUPPORT.', 'Get buckets in comfort all season long. These durable basketball shoes feature a soft heel pillow and a foam midsole for enhanced cushioning and Achilles support as you move up and down the court. The herringbone outsole provides extra grip on the blacktop.'),
('B1007', 'MARQUEE BOOST SHOES', 650.00, 'Basket2Gredmen.jpg', 'grey', 10, 'basketball', 'A CLASSIC B-BALL STYLE DESIGNED FOR EXTRA COMFORT ON THE HARDWOOD.', 'A classic look gets upgraded with modern details. These basketball shoes are built for quickness and agility on the hardwood. They have a moulded ankle collar with a cushioned heel for support and comfort. A responsive midsole returns energy on every jumper while the herringbone outsole provides extra grip as you stop and go on a dime.'), 
('B1008', 'ADIDAS D LILLARD 3', 700.00, 'Basket2Greenwomen.jpg', 'green', 10, 'basketball', '' , 'Humbled by each win and starved by each defeat, Damian Lillard’s style of play is the major inspiration for these basketball sneakers. The D Lillard 3 has a supportive FUSEDMESH upper for a secure lockdown as you break to the basket. Bounce delivers energized cushioning through the clutch. The tread pattern pays tribute to his roots and is inspired by the first courts to see his greatness.
The Adidas D Lillard 3 is built to showcase all of Dame’s elite skills. Scoring, passing, and lockdown defense; the Dame 3 helps you do it all on the court.'),
('B1009', 'HARDEN VOL.3 SHOES', 440.00, 'Basket2Redboys.jpg', 'red', 10, 'basketball', 'B-BALL SHOES INSPIRED BY THE CREATIVITY BEHIND JAMES HARDENS STYLE.
', 'Slow down fast. These basketball shoes are inspired by the free-flowing creativity and movement of James Hardens game. The leather upper provides a stable locked-down feel that supports quick changes of direction. A responsive midsole returns energy on every Euro step, and the herringbone outsole gives you extra traction so you can start and stop on a dime.'),
('B1010', 'PRO ADVERSARY 2019 SHOES', 260.00, 'Basket2Redgirls.jpg', 'red', 10, 'basketball', 'DURABLE B-BALL SHOES BUILT FOR COMFORT AND SUPPORT.', 'Get buckets in comfort all season long. These durable basketball shoes feature a soft heel pillow and a foam midsole for enhanced cushioning and Achilles support as you move up and down the court. The herringbone outsole provides extra grip on the blacktop.'),
('B1011', 'MARQUEE BOOST SHOES', 650.00, 'Basket2Whitemen.jpg', 'white', 10, 'basketball', 'A CLASSIC B-BALL STYLE DESIGNED FOR EXTRA COMFORT ON THE HARDWOOD.', 'A classic look gets upgraded with modern details. These basketball shoes are built for quickness and agility on the hardwood. They have a moulded ankle collar with a cushioned heel for support and comfort. A responsive midsole returns energy on every jumper while the herringbone outsole provides extra grip as you stop and go on a dime.'),
('B1012', 'PRO VISION SHOES', 320.00, 'Basket3Blackgirls.jpg', 'black', 10, 'basketball', 'STREETBALL-INSPIRED B-BALL SHOES DESIGNED FOR A LOCKED-DOWN FEEL.', 'These basketball shoes combine a streetball-inspired look with modern details. Designed with a midfoot cage for a locked-down feel, theyre built with flexible midsole cushioning for soft comfort as you attack the paint. The rubber outsole provides extra grip for quick cuts and pivots on the blacktop.'),
('B1013', 'N3XT L3V3L SHOES', 780.00, 'Basket3Blackmen.jpg', 'black', 10, 'basketball', 'LACELESS B-BALL SHOES DESIGNED FOR A LOCKED-DOWN FEEL.', 'Change directions on a dime. These basketball shoes feature a sock-like construction with a laceless knit upper for a premium locked-down feel. Theyre built with super light Lightstrike cushioning that helps you generate explosive speed for decisive moves up and down the court. A TPU banking barrier offers lateral support for quick side-to-side movement. The herringbone outsole provides extra grip on cuts and pivots.'),
('B1014', 'ADIDAS EXPLOSIVE BOUNCE', 550.00, 'Basket3Redwomen.jpg', 'red', 10, 'basketball', '', 'Explode to the basket with the Adidas Explosive Bounce. The shoes feature a breathable mesh upper and molded heel piece that keep the foot stable while driving and cutting to the hoop. The energy return of Bounce cushioning helps you push the pace while the clock winds down.'),
('B1015', 'N3XT L3V3L SHOES', 780.00, 'Basket3Whitemen.jpg', 'white', 10, 'basketball', 'LACELESS B-BALL SHOES DESIGNED FOR A LOCKED-DOWN FEEL.', 'Change directions on a dime. These basketball shoes feature a sock-like construction with a laceless knit upper for a premium locked-down feel. Theyre built with super light Lightstrike cushioning that helps you generate explosive speed for decisive moves up and down the court. A TPU banking barrier offers lateral support for quick side-to-side movement. The herringbone outsole provides extra grip on cuts and pivots.'),
('B1016', 'PRO SPARK 2018 SHOES', 200.00, 'Basket4Blackgirls.jpg', 'black', 10, 'basketball', 'SHOES DESIGNED FOR SEASON-LONG COMFORT AND DURABILITY.', 'Built to keep you comfortable as you hit clutch shots down the stretch, these kids shoes feature a cushioned midsole and a padded heel for exceptional comfort. The breathable upper and synthetic toe overlay offer durability and lockdown as you suffocate opposition ball handlers with side-to-side movement on every possession.'),
('B1017', 'PRO BOUNCE MADNESS LOW 2019 SHOES', 480.00, 'Basket4Blackmen.jpg', 'black', 10, 'basketball', 'LOW TOP B-BALL SHOES DESIGNED FOR AGILITY AND QUICKNESS.', 'Shake defenders all through the game long. Built for agility, these basketball shoes have a textile upper with a cushioned collar for enhanced ankle support. Responsive cushioning in the midsole lets you hustle up and down the court in comfort. A TPU overlay offers lateral stability for quick side-to-side movement. The herringbone outsole provides extra grip as you cut and pivot to the basket.'),
('B1018', 'MARVELS CAPTAIN MARVEL | PRO', 380.00, 'Basket4Blueboys.jpg', 'blue', 10, 'basketball', 'STREETBALL-INSPIRED B-BALL SHOES DESIGNED FOR A LOCKED-DOWN FEEL.', 'These junior boys basketball shoes mix a streetball-inspired look with modern details. Designed with a midfoot cage for a locked-down feel, they are built with flexible midsole cushioning for soft comfort as you attack the paint. The rubber outsole provides extra grip for quick cuts and pivots on the blacktop.'),
('B1019', 'PRO SPARK 2018 SHOES', 200.00, 'Basket4Bluegirls.jpg', 'blue', 10, 'basketball', 'LOW TOP B-BALL SHOES DESIGNED FOR AGILITY AND QUICKNESS.', 'Shake defenders all through the game long. Built for agility, these basketball shoes have a textile upper with a cushioned collar for enhanced ankle support. Responsive cushioning in the midsole lets you hustle up and down the court in comfort. A TPU overlay offers lateral stability for quick side-to-side movement. The herringbone outsole provides extra grip as you cut and pivot to the basket.'),
('B1020', 'ADIDAS D ROSE 7', 850.00, 'Basket4Bluewomen.jpg', 'blue', 10, 'basketball', '', 'The Adidas D Rose 7 is the third signature shoe of Derrick Rose to have Boost technology in the midsole. It delivers impact protection like no other. The traction of the shoe features a herringbone pattern, letting the player do multidirectional footwork without slipping.
High-top basketball shoes are said to provide more ankle support to hoopers. However, there are those who prefer low-top basketball sneakers because of the increased mobility that they afford. At the same price of $140, wearers may try the low-collared Boost-equipped Harden Vol 3. If mid-top shoes are an alternative, the Adidas Dame 5 is a great go.'),
('B1021', 'PRO SPARK 2018 SHOES', 200.00, 'Basket4Gredgirls.jpg', 'grey', 10, 'basketball', 'LOW TOP B-BALL SHOES DESIGNED FOR AGILITY AND QUICKNESS.', 'Shake defenders all through the game long. Built for agility, these basketball shoes have a textile upper with a cushioned collar for enhanced ankle support. Responsive cushioning in the midsole lets you hustle up and down the court in comfort. A TPU overlay offers lateral stability for quick side-to-side movement. The herringbone outsole provides extra grip as you cut and pivot to the basket.'),
('B1022', 'PRO BOUNCE MADNESS LOW 2019 SHOES', 480.00, 'Basket4Gredmen.jpg', 'grey', 10, 'basketball', 'LOW TOP B-BALL SHOES DESIGNED FOR AGILITY AND QUICKNESS.', 'Shake defenders all through the game long. Built for agility, these basketball shoes have a textile upper with a cushioned collar for enhanced ankle support. Responsive cushioning in the midsole lets you hustle up and down the court in comfort. A TPU overlay offers lateral stability for quick side-to-side movement. The herringbone outsole provides extra grip as you cut and pivot to the basket.'),
('B1023', 'PRO BOUNCE MADNESS LOW 2019 SHOES', 480.00, 'Basket4Whitemen.jpg', 'white', 10, 'basketball', 'LOW TOP B-BALL SHOES DESIGNED FOR AGILITY AND QUICKNESS.', 'Shake defenders all through the game long. Built for agility, these basketball shoes have a textile upper with a cushioned collar for enhanced ankle support. Responsive cushioning in the midsole lets you hustle up and down the court in comfort. A TPU overlay offers lateral stability for quick side-to-side movement. The herringbone outsole provides extra grip as you cut and pivot to the basket.'),
('B1024', 'HARDEN VOL.3 SHOES', 440.00, 'Basket5Blackmen.jpg', 'black', 10, 'basketball', 'B-BALL SHOES INSPIRED BY THE CREATIVITY BEHIND JAMES HARDENS STYLE.', 'Slow down fast. These basketball shoes are inspired by the free-flowing creativity and movement of James Hardens game. The leather upper provides a stable locked-down feel that supports quick changes of direction. A responsive midsole returns energy on every Euro step, and the herringbone outsole gives you extra traction so you can start and stop on a dime.'),
('B1025', 'ADIDAS D ROSE 6 BOOST', 650.00, 'Basket5Blackwomen.jpg', 'black', 10, 'basketball', '', 'The Adidas D Rose 6 Boost is a sneaker packed with Boost technology in the midsole for impact absorption. Something new with the design of this shoe is the external strap on the heel counter. It cups the ankle to make sure the feet is not moving around. Another would be the StableFrame in the midsole that cradles the Boost technology.
Boost is a must-have for most basketball hoopers. James Harden’s third Adidas basketball shoe features the exposed full-length Boost for cushioning. Unlike the Boost in the D Rose 6, the Boost in James Hardens signature basketball shoes are bouncier.'),
('B1026', 'MARQUEE BOOST SHOES', 352.00, 'Basket5Bluegirls.jpg', 'blue', 10, 'basketball','CLASSIC B-BALL SHOES DESIGNED FOR AGILITY ON THE COURT.', 'Updating a classic look with modern details, these low-cut basketball shoes are built for quickness and agility on the hardwood. They feature a molded ankle collar with a cushioned heel for support and comfort. A responsive midsole returns energy on every jumper. The herringbone outsole provides extra grip as you stop and go on a dime.
Endless energyEndless energy
Boost is our most responsive cushioning ever, delivering incredible energy return: The more energy you give, the more you get
Enhanced traction
The zonal herringbone outsole adds extra grip on the court
Padded support
The molded, padded ankle collar offers enhanced comfort'),
('B1027', 'EXPLOSIVE IGNITE 2018 WIDE SHOES', 250.00, 'Basket5Gredboys.jpg', 'grey', 10, 'basketball', 'COMFORTABLE SHOES BUILT WITH EXTRA MIDFOOT STABILITY.', 'These kids shoes are built to help little ones improve their game in comfort. A wider fit offers extra comfort and stability for side-to-side movement, while enhanced cushioning in the midsole and sockliner lets them work on their game all day long. A lightweight upper adds durability to power through the entire season.'),
('B1028', 'HARDEN VOL.3 SHOES', 650.00, 'Basket5Gredmen.jpg', 'grey', 10, 'basketball', 'B-BALL SHOES FOR STOP-AND-START MOVES IN JAMES HARDENS STYLE.', 'Slow down fast. Inspired by his ability to change speed and create space from defenders, these basketball shoes are designed for James Hardens signature style. They are built with a leather upper for a locked-down feel that supports quick changes of direction. A responsive midsole returns energy on every Euro step. The herringbone outsole provides extra traction as you start and stop on a dime.'),
('B1029', 'MARQUEE BOOST SHOES', 352.00, 'Basket5Redgirls.jpg', 'red', 10, 'basketball', 'CLASSIC B-BALL SHOES DESIGNED FOR AGILITY ON THE COURT.', 'Updating a classic look with modern details, these low-cut basketball shoes are built for quickness and agility on the hardwood. They feature a molded ankle collar with a cushioned heel for support and comfort. A responsive midsole returns energy on every jumper. The herringbone outsole provides extra grip as you stop and go on a dime.
Endless energyEndless energy
Boost is our most responsive cushioning ever, delivering incredible energy return: The more energy you give, the more you get
Enhanced traction
The zonal herringbone outsole adds extra grip on the court
Padded support
The molded, padded ankle collar offers enhanced comfort'),
('B1030', 'EXPLOSIVE IGNITE 2018 WIDE SHOES', 250.00, 'Basket5Gredboys.jpg', 'grey', 10, 'basketball', 'COMFORTABLE SHOES BUILT WITH EXTRA MIDFOOT STABILITY.', 'These kids shoes are built to help little ones improve their game in comfort. A wider fit offers extra comfort and stability for side-to-side movement, while enhanced cushioning in the midsole and sockliner lets them work on their game all day long. A lightweight upper adds durability to power through the entire season.');