INSERT INTO `product` (`id`, `name`, `price`, `image`, `color`, `quantity`, `style`, `title`, `description`) VALUES
('T1001', 'ALPHABOUNCE 1 PARLEY SHOES', 294.00, 'TrainingKidsBoyAlphabounce1Parley.jpg', 'black', 10, 'training', 'CUSHIONED SHOES MADE WITH PARLEY OCEAN PLASTIC™ YARN.', 'These juniors running shoes are designed with a seamless mesh upper that supports and flexes with your foot through the gait cycle. Underfoot, Bounce provides comfortable cushioning.
adidas is dedicated to creating products in ways that minimise their environmental impact. This product is created with yarn made in collaboration with Parley for the Oceans. Some of the yarn features Parley Ocean Plastic™ which is made from recycled waste, intercepted from beaches and coastal communities before it reaches the ocean.'), 
('T1002', 'PUREBOOST GO SHOES', 440.00, 'TrainingKidsBoyPureboostGo.jpg', 'grey', 10, 'training', 'LIGHTWEIGHT, SUPPORTIVE SHOES FOR CITY RUNNING.', 'Designed for the uneven sidewalks, rain-slick pavement and unexpected obstacles of urban running. These juniors neutral shoes have a wider forefoot platform and higher heel for increased stability. A lightweight knit upper hugs and supports the foot. Responsive cushioning returns energy with every stride.'), 
('T1003', 'RAPIDARUN KNIT SHOES', 226.00, 'TrainingKidsBoyRapidunKnit.jpg', 'black', 10, 'training', 'CUSHIONING RUNNING SHOES FOR A COMFORTABLE RIDE.', 'These juniors shoes offer performance with every stride. The adaptive knit upper moves naturally with every footstrike, while a Cloudfoam midsole offers pillow-soft cushioning for long-lasting comfort. A running-specific outsole and targeted support in key areas round out the design.'), 
('T1004', 'RAPIDARUN LACELESS SHOES', 300.00, 'TrainingKidsBoyRapidunLaceles.jpg', 'black', 10, 'training', 'LIGHTWEIGHT, SUPPORTIVE SHOES FOR CITY RUNNING.', 'Designed for the uneven sidewalks, rain-slick pavement and unexpected obstacles of urban running. These juniors neutral shoes have a wider forefoot platform and higher heel for increased stability. A lightweight knit upper hugs and supports the foot. Responsive cushioning returns energy with every stride.'), 
('T1005', 'ULTRABOOST SHOES', 800.00, 'TrainingKidsBoyUltraboost.jpg', 'grey', 10, 'training', 'JUNIORS RUNNING SHOES FOR RESPONSIVE ENERGY RETURN.', 'Whether you are sprinting past competitors or hanging with the pack, these juniors running shoes are designed to help you reach your goals. They have responsive cushioning for endless energy return. The knit upper wraps around your foot for a supportive feel while the grippy rubber outsole delivers traction on unpredictable surfaces.'), 
('T1006', 'ALPHABOUNCE BEYOND SHOES', 300.00, 'TrainingKidsGirlAlphabounceBeyond.jpg', 'blue', 10, 'training', 'NEUTRAL RUNNING SHOES WITH A SOCK-LIKE FIT AND CUSHIONED COMFORT.', 'With the smooth construction of a Forgedmesh upper, these juniors running shoes deliver a comfortable, foot-hugging fit. Bounce cushioning provides flexible comfort for leaps and sprints during after-school sports.'), 
('T1007', 'ALPHABOUNCE INSTINCT SHOES', 259.00, 'TrainingKidsGirlAlphabounceInstint.jpg', 'grey', 10, 'training', 'VERSATILE RUNNING SHOES WITH TARGETED SUPPORT.', 'Made for cross training, these juniors neutral running shoes have a seamless, supportive mesh upper. Strategic zones of reinforcement support lateral as well as linear movement. The flexible midsole offers enhanced cushioning and allows the foot to move naturally.'), 
('T1008', '24/7 SHOES', 360.00, 'TrainingWomen24shoes.jpg', 'grey', 10, 'training', 'LIGHTWEIGHT TRAINING SHOES WITH STEP-IN COMFORT.', 'Made for cross training, these juniors neutral running shoes have a seamless, supportive mesh upper. Strategic zones of reinforcement support lateral as well as linear movement. The flexible midsole offers enhanced cushioning and allows the foot to move naturally.'),
('T1009', '24/7 SHOES', 360.00, 'TrainingWomen24shoes1.jpg', 'black', 10, 'training', 'LIGHTWEIGHT TRAINING SHOES WITH STEP-IN COMFORT.', 'Made for cross training, these juniors neutral running shoes have a seamless, supportive mesh upper. Strategic zones of reinforcement support lateral as well as linear movement. The flexible midsole offers enhanced cushioning and allows the foot to move naturally.'),
('T1010', 'CRAZYTRAIN ELITE SHOES', 455.00, 'TrainingWomenCrazyTrainElite.jpg', 'black', 10, 'training', 'MULTISPORT TRAINING SHOES WITH RESPONSIVE CUSHIONING.', 'These shoes have a training-specific design that supports multidirectional movement. The lightweight mesh upper hugs the foot with a sock-like fit. Built-in midfoot support provides stability, and forefoot flex gives you a wide range of motion. Responsive cushioning returns energy to your stride.'),
('T1011', 'CRAZYTRAIN LT SHOES', 140.00, 'TrainingWomenCrazyTrainLT1.jpg', 'red', 10, 'training', 'LIGHTWEIGHT TURF SHOES MADE FOR CROSS TRAINING.', 'Push past plateaus in these men or women turf training shoes. Dual-density Bounce for energised comfort and a lightweight build with a breathable mesh upper helps keep you going. The PU overlays and rubber outsole add stability and traction for quick direction changes.'),
('T1012', 'EDGEBOUNCE SHOES', 266.00, 'TrainingWomenCrazyTrainPro.jpg', 'black', 10, 'training', 'INSPIRED BY CREATORS, DESIGNED TO STAND OUT, CURATED FOR YOU.', 'Part of a statement collection inspired by Stella McCartney, these neutral running shoes are geared for gym floors or pavement. The womens-specific design features a wider forefoot and heel platform to deliver stability while cross training. The shoes have a stretch mesh upper that offers foot-cradling comfort.'),
('T1013', 'EDGEBOUNCE SHOES', 266.00, 'TrainingWomenEdgebounce1.jpg', 'white', 10, 'training', 'INSPIRED BY CREATORS, DESIGNED TO STAND OUT, CURATED FOR YOU.', 'Part of a statement collection inspired by Stella McCartney, these neutral running shoes are geared for gym floors or pavement. The womens-specific design features a wider forefoot and heel platform to deliver stability while cross training. The shoes have a stretch mesh upper that offers foot-cradling comfort.'),
('T1014', 'PUREBOOST X TR 3.0 LL SHOES', 280.00, 'TrainingWomenPureboostXTR3.0LL1.jpg', 'blue', 10, 'training', 'LACELESS HIGH CUTS WITH A WOMENS-SPECIFIC ARCH DESIGN.
', 'Made for the athlete who likes to mix it up, these shoes have a progressive design, with a womens-specific arch that cradles the foot for a unique compression fit. The slip-on shoes have a knit upper with wraparound bands that hug the foot for support and stretch in any direction.'),
('T1015', 'CRAZYTRAIN ELITE SHOES', 240.00, 'TrainingWomenSolarLT1.jpg', 'white', 10, 'training', 'LIGHTWEIGHT SHOES READY FOR ANY TYPE OF WORKOUT.', 'Versatile enough for a variety of workouts, these shoes are made for the athlete who mixes up barbell exercises one day with agility drills or speedwork the next. The textile upper is lightweight and flexible while providing the lockdown you need when moving side-to-side. It rides on a cushioned midsole that feels springy and flexible.'),
('T1016', 'ULTRABOOST X ALL TERRAIN', 700.00, 'TrainingWomenUltraboostXAllTerrain.jpg', 'grey', 10, 'training', 'MODERN SLIP-ON RUNNING SHOES CREATED WITH STELLA MCCARTNEY.', 'Innovative style thats pure Stella. These streamlined running shoes have a slip-on design that wraps the foot in supportive comfort. With a mid cut, they ride on a rubber outsole that grips the pavement in wet conditions. Matte and shiny overlays add an eye-catching finish.'),
('T1017', 'TERREX TRACEROCKER SHOES', 350.00, 'TraningTerrexTracerocker.jpg', 'black', 10, 'training', 'CORE BLACK/CORE BLACK/UTILITY BLACK', 'Lightweight and durable, these mens trail running shoes are designed for light trails. They feature a breathable mesh upper and EVA midsole cushioning. A rugged TRAXION™ outsole maximises grip in all directions.');